// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArj1RYqjjtaHmmf9qbloMseRnAGLojWOc',
    appId: '1:403093956874:android:8377338fd40fd4cad9b2f3',
    messagingSenderId: '403093956874',
    projectId: 'nool-e4a78',
    storageBucket: 'nool-e4a78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjqVSpNENGUUdA_zUaFRFBH44TesQEzw',
    appId: '1:403093956874:ios:95c04247c0bb9518d9b2f3',
    messagingSenderId: '403093956874',
    projectId: 'nool-e4a78',
    storageBucket: 'nool-e4a78.appspot.com',
    iosClientId:
        '403093956874-64q0t1d0jk0aajnnjsmsej2i090lnt1j.apps.googleusercontent.com',
    iosBundleId: 'com.nitrocomputersolutions.nool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCbnCd5De6C9Yapr5XccR4tixnzuQ3XZes",
    authDomain: "nool-e4a78.firebaseapp.com",
    projectId: "nool-e4a78",
    storageBucket: "nool-e4a78.appspot.com",
    messagingSenderId: "403093956874",
    appId: "1:403093956874:web:f4166de3864b4ebcd9b2f3",
  );
}
*/
